
package th.co.nssol.services.model.logic.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Tue May 22 15:54:03 ICT 2018
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "getInterfaceData", namespace = "http://logic.model.services.nssol.co.th/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getInterfaceData", namespace = "http://logic.model.services.nssol.co.th/")

public class GetInterfaceData {

    @XmlElement(name = "object")
    private java.lang.String object;

    public java.lang.String getObject() {
        return this.object;
    }

    public void setObject(java.lang.String newObject)  {
        this.object = newObject;
    }

}

