
package th.co.nssol.services.model.logic.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.4
 * Mon Jul 23 15:53:46 ICT 2018
 * Generated source version: 3.2.4
 */

@XmlRootElement(name = "getMasterData", namespace = "http://logic.model.services.nssol.co.th/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMasterData", namespace = "http://logic.model.services.nssol.co.th/", propOrder = {"function", "object", "userId"})

public class GetMasterData {

    @XmlElement(name = "function")
    private java.lang.String function;
    @XmlElement(name = "object")
    private java.lang.String object;
    @XmlElement(name = "userId")
    private java.lang.String userId;

    public java.lang.String getFunction() {
        return this.function;
    }

    public void setFunction(java.lang.String newFunction)  {
        this.function = newFunction;
    }

    public java.lang.String getObject() {
        return this.object;
    }

    public void setObject(java.lang.String newObject)  {
        this.object = newObject;
    }

    public java.lang.String getUserId() {
        return this.userId;
    }

    public void setUserId(java.lang.String newUserId)  {
        this.userId = newUserId;
    }

}

