//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8831
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FATHBarcode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FATHBarcode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to submit?.
        /// </summary>
        internal static string CFM_01 {
            get {
                return ResourceManager.GetString("CFM_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete?.
        /// </summary>
        internal static string CFM_02 {
            get {
                return ResourceManager.GetString("CFM_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear all scanned data?.
        /// </summary>
        internal static string CFM_03 {
            get {
                return ResourceManager.GetString("CFM_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect User ID/Password.
        /// </summary>
        internal static string ERR_01 {
            get {
                return ResourceManager.GetString("ERR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Delivery Order.
        /// </summary>
        internal static string ERR_02 {
            get {
                return ResourceManager.GetString("ERR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part no. is not existing in DO .
        /// </summary>
        internal static string ERR_03 {
            get {
                return ResourceManager.GetString("ERR_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty exceeds the needed qty.
        /// </summary>
        internal static string ERR_04 {
            get {
                return ResourceManager.GetString("ERR_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Tag No..
        /// </summary>
        internal static string ERR_05 {
            get {
                return ResourceManager.GetString("ERR_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tag No. to pick.
        /// </summary>
        internal static string ERR_06 {
            get {
                return ResourceManager.GetString("ERR_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are older parts to pick, cannot pick this part.
        /// </summary>
        internal static string ERR_07 {
            get {
                return ResourceManager.GetString("ERR_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to complete all parts.
        /// </summary>
        internal static string ERR_08 {
            get {
                return ResourceManager.GetString("ERR_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to pass all parts checking.
        /// </summary>
        internal static string ERR_09 {
            get {
                return ResourceManager.GetString("ERR_09", resourceCulture);
            }
        }
    }
}
